# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/wp-content/plugins/laurenstyle

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      # TO DO run tests!

      - run:
          name: build gutenblocks
          command: npm run build

      - run:
          name: Deploy to WPE
          command: |
            chmod +x deploy.sh
            ./deploy.sh
